server:
  port: 8087
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
spring:
  application:
    name: AUDITOR-SERVICE
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    
  datasource:
    url: jdbc:h2:mem:my_db
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
developerUrl: http://DEVELOPER-SERVICE:8088/dev/audit/

testerUrl: http://TESTER-SERVICE:8089/tester/audit/