
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
          
server:
  port: 8088

spring:
  application:
    name: DEVELOPER-SERVICE
    
  h2:
    console:
      enabled: true
      
  datasource:
    url: jdbc:h2:mem:my_db
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
    
  jpa:
    hibernate:
      ddl-auto: create-drop
      


  