server:
  port: 8089
  
spring:
  application:
    name: TESTER-SERVICE
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    
  datasource:
    url: jdbc:h2:mem:my_db
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
          